<?php

namespace AppBundle\Repository;

/**
 * TemplateChampsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemplateChampsRepository extends \Doctrine\ORM\EntityRepository
{
}
