app_cv:
    resource: "@AppBundle/Controller/CvController.php"
    type:     annotation

app_sections:
    resource: "@AppBundle/Controller/SectionsController.php"
    type:     annotation

app_groupes:
    resource: "@AppBundle/Controller/GroupesController.php"
    type:     annotation

app_templates:
    resource: "@AppBundle/Controller/TemplatesController.php"
    type:     annotation

app_champs:
    resource: "@AppBundle/Controller/ChampsController.php"
    type:     annotation

test:
    resource: "@TestBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
#fos_user:
 #   resource: "@FOSUserBundle/Resources/config/routing/all.xml"


fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_profile_admin:
    resource: "@FOSUserBundle/Resources/config/routing/profile_admin.xml"
    prefix: /profile_admin

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile